#!/bin/bash

# JankyBorders Configuration - Catppuccin Mocha Aesthetic
# Active window: Catppuccin Blue (#89b4fa) to Mauve (#cba6f7) gradient
# Inactive window: Catppuccin Surface0 (#313244) border

borders \
    style=round \
    width=4.0 \
    hidpi=on \
    ax_focus=off \
    active_color="gradient(top_left=0xff89b4fa,bottom_right=0xffcba6f7)" \
    inactive_color="0xaa313244"

